# Generated by Django 4.0.4 on 2022-05-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_pic',
            field=models.CharField(default='Add a display picture here', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Add your bio here', max_length=300),
        ),
    ]
