# Generated by Django 4.0.4 on 2022-05-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
