# Generated by Django 4.0.4 on 2022-05-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_display_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='submissions',
        ),
    ]
