# Generated by Django 4.0.4 on 2022-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=50)),
                ('image', models.CharField(default=None, max_length=50)),
                ('submitted_by', models.CharField(default=None, max_length=50)),
                ('date_submitted', models.DateField(default=None)),
                ('text_field', models.CharField(default=None, max_length=2000)),
            ],
        ),
    ]
