# Generated by Django 4.0.4 on 2022-05-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default=None, max_length=200)),
                ('submitted_by', models.CharField(default=None, max_length=50)),
                ('date_submitted', models.DateField(default=None)),
                ('text_field', models.CharField(default=None, max_length=2000)),
                ('category', models.TextField(choices=[('at', 'Art'), ('hi', 'History'), ('ph', 'Philosophy'), ('po', 'Politics'), ('pm', 'Poetry'), ('ms', 'Misc')], default=None)),
            ],
        ),
    ]
