# Generated by Django 4.0.4 on 2022-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submissions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='category',
            field=models.TextField(choices=[('at', 'Art'), ('hi', 'History'), ('ph', 'Philosophy'), ('po', 'Politics'), ('pm', 'Poetry'), ('ms', 'Misc')], default=None),
        ),
    ]
