# Generated by Django 4.0.4 on 2022-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submissions_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='date_submitted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
