# Generated by Django 4.0.4 on 2022-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submissions_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
