# Generated by Django 4.0.4 on 2022-04-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submissions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='image',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
