# Generated by Django 4.0.4 on 2022-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_submissions_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
