# Generated by Django 4.0.4 on 2022-05-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_submissions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='category',
            field=models.TextField(choices=[('art', 'Art'), ('history', 'History'), ('philosophy', 'Philosophy'), ('politics', 'Politics'), ('poetry', 'Poetry'), ('film_studies', 'Film studies')], default=None),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='text_field',
            field=models.CharField(default=None, max_length=6000),
        ),
    ]
